# Generated by Django 4.1.1 on 2022-10-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OwnerPanel', '0002_remove_listing_photo_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(default='', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
