# Generated by Django 4.1.1 on 2022-10-16 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OwnerPanel', '0004_alter_listing_photo_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='photo_main',
            new_name='photo',
        ),
    ]
