# Generated by Django 4.1.1 on 2022-10-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OwnerPanel', '0006_alter_listing_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
