# Generated by Django 4.1.1 on 2022-10-16 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OwnerPanel', '0008_alter_listing_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
