# Generated by Django 4.1.1 on 2022-10-21 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OwnerPanel', '0010_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='title',
            new_name='Hostel_Name',
        ),
    ]
