# Generated by Django 4.1.1 on 2022-10-21 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OwnerPanel', '0013_remove_listing_hostel_name_listing_photo_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='title',
            new_name='Hostel_Name',
        ),
    ]
