# Generated by Django 4.1.1 on 2022-10-21 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OwnerPanel', '0014_rename_title_listing_hostel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='Hostel_Name',
            new_name='title',
        ),
    ]
