# Generated by Django 4.1.1 on 2022-10-16 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
        ('listings', '0005_remove_listing_bathrooms_remove_listing_bedrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='realtor',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor'),
            preserve_default=False,
        ),
    ]
