bedroom_choices = {
  '1':1,
  '2':2,
  '3':3,
  '4':4,
  '5':5,
  '6':6,
  '7':7,
  '8':8,
  '9':9,
  '10':10
  }

price_choices = {
  '1000':'₹1000',
  '2000':'₹2000',
  '3000':'₹3000',
  '4000':'₹4000',
  '5000':'₹5000',
  '6000':'₹6000',
  '7000':'₹7000',
  '8000':'₹8000',
  '9000':'₹9000',
  '10000':'₹10000',
}

state_choices = {

        'All': 'Ajmer',
        'AWR': 'Alwar',
        'BWA': 'Banswara',
        'BAZ': 'Baran',
        'BME': 'Barmer',
        'BTE': 'Bharatpur',
        'BHL': 'Bhilwara',
        'BKN': 'Bikaner',
        'BUDI': 'Bundi',
        'COR': 'Chittorgarh',
        'CUR': 'Churu',
        'DO': 'Dausa',
        'DHO': 'Dholpur',
        'HMH': 'Hanumangarh',
        'JP': 'Jaipur',
        'JSM': 'Jaisalmer',
        'JOR': 'Jalore',
        'JHW': 'Jhalawar',
        'JJN': 'Jhunjhunu',
        'JU': 'Jodhpur',
        'KRL': 'Karauli',
        'KOTA': 'Kota',
        'NGO': 'Nagaur',
        'PALI': 'Pali',
        'RPZ': 'Pratapgarh',
        'RSD': 'Rajsamand',
        'SWM': 'Sawai Madhopur',
        'SIKR': 'Sikar',
        'SIRO': 'Sirohi',
        'SGGN': 'Sri Ganganagar',
        'TK': 'Tonk',
        'UDZ': 'Udaipur',

}